Also return remaining bytes in `FromBytes` conversion methods
google/zerocopy pull request #1059
Opened 2024-03-19 22:25 UTC by jswrenn

This change makes the slice and non-slice conversion methods consistent, and provides a lightweight way (i.e., without `Ref`) to access the leftover bytes after conversions.

This PR tests out the 'feel' of tuple-returning conversion methods. Alternatively, we could provide a mirror set of `_split`  methods.

Addresses #1051.

2024-03-20 16:03 UTC, smalis-msft commented
While I'm obviously in favor of doing this in general, I feel like modifying the existing methods would be too large of a breaking change to be worthwhile, which was why I suggested new methods.

2024-03-20 16:35 UTC, jswrenn commented
Hm, we'll need to balance the costs of subjecting current users to breaking changes, against the costs of subjecting current and future users to a more bloated API.  Adding `_split` methods consistently would require adding eight additional methods to `FromBytes` (which has 14 methods in our latest 0.8 pre-release):
```diff
  mut_from
  mut_from_prefix
+ mut_from_prefix_split
  mut_from_suffix
+ mut_from_suffix_split
  mut_slice_from
  mut_slice_from_prefix
+ mut_slice_from_prefix_split
  mut_slice_from_suffix
+ mut_slice_from_suffix_split
  read_from
  read_from_prefix
+ read_from_prefix_split
  read_from_suffix
+ read_from_suffix_split
  ref_from
  ref_from_prefix
+ ref_from_prefix_split
  ref_from_suffix
+ ref_from_suffix_split
  slice_from_prefix
  slice_from_suffix
```
That's quite a hefty addition, and whatever course of action we take here will also likely be taken for our upcoming [`TryFromBytes`](https://docs.rs/zerocopy/0.8.0-alpha.7/zerocopy/trait.TryFromBytes.html) trait, too.

Since we're preparing for a major breaking release anyways, we have a bit more license than usual to consider breaking changes.

2024-03-30 00:16 UTC, kupiakos commented
As I discuss in https://github.com/google/zerocopy/issues/884#issuecomment-2027828809, I'm strongly in support of _not_ removing the plain-casting methods that don't return the suffix. **The code should do the minimum work necessary for what's needed.**

I personally find the zerocopy APIs lacking in useful transitive operations like this, so I would prefer the "bloat" of adding these methods and keeping the plain-casting ones.

What do you think of these methods starting with `split_` instead of ending in `_split`? `split_mut_from_prefix` reads clearly in the imperative mood and highlights that it's doing more than just a bounds-check and pointer cast: it's splitting as well. This **split is an extra operation**, both cognitively and for the compiler.

I don't care about the `*_from_suffix` API and I don't know who does - all I ask is that there's consistency where it makes sense. Perhaps as a middle ground, this PR can introduce only splitting versions for the `prefix` APIs, which adds 5 methods instead of 10:

```diff
  mut_from
  mut_from_prefix
+ split_mut_from_prefix
  mut_from_suffix
  mut_slice_from
  mut_slice_from_prefix
+ split_mut_slice_from_prefix
  mut_slice_from_suffix
  read_from
  read_from_prefix
+ split_read_from_prefix
  read_from_suffix
  ref_from
  ref_from_prefix
+ split_ref_from_prefix
  ref_from_suffix
  slice_from_prefix
+ split_slice_from_prefix
  slice_from_suffix
```

2024-04-01 13:46 UTC, smalis-msft commented
> I don't care about the *_from_suffix API and I don't know who does
We use it for parsing certain things as well as prefix, and would strongly prefer to have split versions of it as well if you decide to go this route.

2024-04-05 20:21 UTC, jswrenn commented
I've made a discussion post exploring some of the naming and return type design space: https://github.com/google/zerocopy/discussions/1095

2024-04-19 18:53 UTC, joshlf commented
I'm inclined to merge this based on the following reasoning:
- The ergonomics of discarding an unneeded prefix/suffix are better than the ergonomics of reconstructing a prefix/suffix if one isn't returned by the API
- From what little visibility we have into use cases in the ecosystem, it seems that wanting the prefix/suffix is the more common situation
- For users who care about not relying on the compiler to perform optimizations, techniques like the one described in [this comment](https://github.com/google/zerocopy/issues/884#issuecomment-2043538316) are available
- More generally, we are aware that our current internal software organization is based on the assumption that the compiler will aggressively optimize, and we are actively considering how to provide better support for users who aren't comfortable with this situation: https://github.com/google/zerocopy/issues/1125

2024-04-19 18:57 UTC, joshlf requested changes

2024-04-19 18:57 UTC, joshlf commented on src/lib.rs
> +    /// bytes. If `bytes.len() < size_of::<Self>()` or the suffix of `bytes` is
To make it more clear that it's the prefix, not the suffix, that is returned:

```suggestion
    /// bytes of `bytes` interpreted as `Self`, and a reference to the preceding
    /// bytes. If `bytes.len() < size_of::<Self>()` or the suffix of `bytes` is
```

2024-04-19 18:57 UTC, joshlf commented on src/lib.rs
> +    /// bytes. If `bytes.len() < size_of::<Self>()` or the suffix of `bytes` is
```suggestion
    /// This method returns both a reference to the last `size_of::<Self>()`
    /// bytes of `bytes` interpreted as `Self`, and a reference to the preceding
    /// bytes. If `bytes.len() < size_of::<Self>()` or the suffix of `bytes` is
```

2024-04-23 19:40 UTC, joshlf approved these changes

2024-04-23 19:58 UTC, merged