aarch64 fix for big endian types
google/zerocopy pull request #1786
Opened 2024-10-01 08:10 UTC by lucarlig

NEON intrinsics are not supported on aarch64 big endian targets. Change to use fall back types for big endian aarch64.
tested on aarch64_be-unknown-linux-gnu_ilp32 and aarch64_be-unknown-linux-gnu

2024-10-02 17:14 UTC, joshlf commented
Thanks for this! A few small things:
- Can you rebase on `main` and force-push this as a single commit?
- Can you update your commit message to follow our [commit message format](https://github.com/google/zerocopy/discussions/1318)?
- Is there a citation for the fact that NEON intrinsics aren't supported on big-endian targets? If you could add a comment with a citation in the source code, that'd be good.
- Can you add an `include` section [here](https://github.com/google/zerocopy/blob/8abf7dacd56339e7a232bf7e2ec4906edc3d4a26/.github/workflows/ci.yml#L242) and use [matrix includes](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#expanding-or-adding-matrix-configurations) to add the following two build combinations. Please add a comment that references this PR and explains why we test on these combinations.
  - `toolchain: nightly` / `target: aarch64_be-unknown-linux-gnu_ilp32` / `features: --all-features` / `crate: zerocopy`
  - `toolchain: nightly` / `target: aarch64_be-unknown-linux-gnu` / `features: --all-features` / `crate: zerocopy`

2024-10-02 18:21 UTC, lucarlig commented
@joshlf  fixed the stuff that you requested,
this is the issue you are looking for as evidence https://github.com/rust-lang/stdarch/issues/1484
I don't think the ilp32 version tests anything different so I skipped including that

2024-10-02 18:31 UTC, lucarlig commented
it's failing because 'aarch64_be-unknown-linux-gnu' is not provided by rustup, only rustc
to test should do something like:
```
cargo build --target=aarch64_be-unknown-linux-gnu -Zbuild-std
```

2024-10-02 19:16 UTC, joshlf commented
> it's failing because 'aarch64_be-unknown-linux-gnu' is not provided by rustup, only rustc to test should do something like:
> 
> ```
> cargo build --target=aarch64_be-unknown-linux-gnu -Zbuild-std
> ```

Ah gotcha. I confirmed locally that this works:

```shell
$ ./cargo.sh +nightly build --target=aarch64_be-unknown-linux-gnu -Zbuild-std --features simd
```

Can you add a new build target (under `kani` and before `check_fmt`) that runs that command? That can replace the other changes to `.github/workflows/ci.yml`.

2024-10-02 19:17 UTC, joshlf requested changes

2024-10-02 19:17 UTC, joshlf commented on src/impls.rs
> +            #[cfg(all(target_arch = "aarch64", target_endian = "little"))]
```suggestion
            // NOTE(https://github.com/rust-lang/stdarch/issues/1484): NEON intrinsics are currently
            // broken on big-endian platforms.
            #[cfg(all(target_arch = "aarch64", target_endian = "little"))]
```

2024-10-02 21:53 UTC, joshlf approved these changes
Okay amazing, thank you for your work on this! Once this merges, I can publish a new release that includes it.

2024-10-02 21:57 UTC, joshlf commented
Unfortunately I think that the build failure you're currently seeing is going to require you to compute the correct nightly to install based on the contents of `Cargo.toml`. You can extract that via `./cargo.sh --version nightly` and then tell the GitHub action to install that particular nightly.

Here's how we do that in the build matrix - here it should be much simpler because you only need to support a single toolchain and none of the Miri stuff is relevant:

https://github.com/google/zerocopy/blob/a9f09d7afc526a3a54a7a37b991eca0f22358950/.github/workflows/ci.yml#L264-L321

2024-10-02 22:42 UTC, lucarlig commented
@joshlf not sure what dependency is missing

2024-10-02 22:59 UTC, joshlf requested changes

2024-10-02 22:59 UTC, joshlf commented on .github/workflows/ci.yml
> +          MIRIFLAGS="$MIRIFLAGS $ZC_NIGHTLY_MIRIFLAGS"
I don't believe you need this since we don't use Miri in this job.

```suggestion
```

2024-10-02 22:59 UTC, joshlf commented on .github/workflows/ci.yml
> +          echo "MIRIFLAGS=$MIRIFLAGS" >> $GITHUB_ENV
Same here.

```suggestion
```

2024-10-02 22:59 UTC, joshlf commented on .github/workflows/ci.yml
> +            components: clippy, rust-src, miri
Do you need `miri`?

2024-10-02 22:59 UTC, joshlf commented
> @joshlf not sure what dependency is missing

You need to edit this line:

https://github.com/google/zerocopy/blob/a9f09d7afc526a3a54a7a37b991eca0f22358950/.github/workflows/ci.yml#L707

...to include `check_be_aarch64`

2024-10-03 10:51 UTC, joshlf approved these changes

2024-10-03 12:36 UTC, joshlf commented
Thanks again for your work on this!

2024-10-03 13:02 UTC, merged

2024-10-06 21:27 UTC, workingjubilee commented
Please fix this by fixing the intrinsics upstream. Fixing this in every single crate is not less effort than fixing it in stdarch: https://github.com/rust-lang/stdarch/issues/1484#issuecomment-1942934003

2024-10-06 21:49 UTC, joshlf commented
@workingjubilee is the lack of support in zerocopy breaking you? I'm hesitant for us to own a fix in stdarch unless there are users who actively need this feature.

2024-10-07 19:08 UTC, joshlf commented
> @joshlf Just to be clear, you're fine. If you want to accept this fix, that's okay. But I just don't think that fixing zerocopy, memchr, half, etc., in a fix that might be best-off reverted once stdarch is fixed, is better than fixing stdarch.

Okay gotcha, that makes senes.