rename `FromZeroes` to `FromZeros`
google/zerocopy pull request #430
Opened 2023-09-29 18:14 UTC by jswrenn

Pretend you didn't see this.

`FromZeroes` is retained as a deprecated, `doc(hidden)` re-export.

Additionally, for consistency, `LayoutVerified` is changed from a type alias to `pub use ... as ...` reexport.

2023-09-29 18:14 UTC, jswrenn commented on src/lib.rs
> +pub use Ref as LayoutVerified;
^

2023-09-29 18:14 UTC, jswrenn commented on src/lib.rs
> +pub use FromZeros as FromZeroes;
^

2023-09-29 18:18 UTC, joshlf commented on src/lib.rs
> +#[deprecated(since = "0.7.6", note = "FromZeroes has been renamed to FromZeros")]
Deprecating is a breaking change for users who deny warnings in their dependencies; we need to wait for 0.8 to mark this as deprecated.

2023-09-29 18:22 UTC, joshlf requested changes

2023-09-29 18:22 UTC, joshlf commented on src/lib.rs
> +pub use FromZeros as Fromzeros;
s/Fromzeroes/FromZeroes

2023-12-07 18:34 UTC, joshlf requested changes
There are some files with the `zeroes` spelling in the name that need to be changed, but otherwise LGTM!

2023-12-07 18:36 UTC, joshlf requested changes
Also, can you update the commit message?
- Capitalize "rename" in the summary line
- Mention that "zeroes" is a valid spelling, but that "zeros" is more commonly accepted, possibly citing [this StackExchange answer](https://english.stackexchange.com/questions/3824/what-is-the-plural-form-of-zero/3825#3825)
- Add `Closes #431` at the end

2023-12-07 18:48 UTC, joshlf requested changes
In the commit message:

> Although both spelling are acceptable

Should be "spellings" plural.

2023-12-07 18:49 UTC, joshlf approved these changes

2023-12-07 19:00 UTC, merged

2023-12-07 19:23 UTC, jswrenn commented on src/lib.rs
> +pub use FromZeros as FromZeroes;
This is going to use-rename both the trait *and* the proc macro (if it's in scope from the `derive`).