Safety comments status updates
google/zerocopy pull request #433
Opened 2023-09-29 21:57 UTC by samuelselleck

While reading through some of the code I added some quotes and TODOs here and there related to #429.

2023-10-11 23:01 UTC, joshlf requested changes
Awesome, thank you so much for these! This is exactly what we're looking for. A few minor style nits, but the content is good.

2023-10-11 23:01 UTC, joshlf commented on src/lib.rs
> +    /// [1] TODO(https://doc.rust-lang.org/nightly/core/num/struct.Wrapping.html#layout-1):
```suggestion
    /// [1] TODO(https://doc.rust-lang.org/nightly/core/num/struct.Wrapping.html#layout-1):
    ///     Reference this documentation once it's available on stable.
```

2023-10-13 19:38 UTC, samuelselleck commented
Thank you for your feedback! Don't worry about being picky, that's the kind of thing I'm looking to learn :)

I think I've addressed all of your comments, if there is anything else do let me know!

**Question**: The code still contains safety comments (starting with //SAFETY:) that are not wrapped in the safety_comment! macro. Is this intentional and if so what is the purpose of the differentiation?

(I had some git problems, but think they are fixed? (accidentally merged upstream changes through the github gui). If anything is off do let me know and I'll try to figure it out.)

2023-10-15 18:40 UTC, joshlf commented
> I think I've addressed all of your comments, if there is anything else do let me know.

Awesome, thanks! I'll try to get to these soon.

> **Question**: The code still contains safety comments (starting with //SAFETY:) that are not wrapped in the safety_comment! macro. Is this intentional and if so what is the purpose of the differentiation?

Yeah, that's intentional. Normally you'd just put a `// SAFETY:` comment on each `unsafe` block. The reason for the `safety_comment!` macro is that we often have a lot of `unsafe` trait impls whose soundness is based on identical or very similar arguments, and so we'd _like_ to be able to write a single `// SAFETY:` comment to annotate multiple such impls. Since there's no way to do this that is legible to Clippy, we use the `safety_comment!` macro instead, which under the hood just annotates each macro invocation with `#[allow(clippy::undocumented_unsafe_blocks)]`:

https://github.com/google/zerocopy/blob/9ce05f8fa5c4761020c082ce18f071007125902f/src/macros.rs#L24-L29

> (I had some git problems, but think they are fixed? (accidentally merged upstream changes through the github gui). If anything is off do let me know and I'll try to figure it out.)

Seems fine to me 🤷‍♂️  We have this repo configured to squash all commits into a single one when a PR is merged, so it probably doesn't make much of a difference (perhaps with the exception that the resulting commit message will include a summary of each commit that was included in the PR). Personally my flow is to always just edit the commit and then force push, but whatever flow works for you is fine.

2023-10-16 18:50 UTC, samuelselleck commented
Thanks for the explanation of the safety_comment macro, that makes sense! I'll adopt the same push -f method for edits in the future :)

2023-10-19 04:32 UTC, joshlf requested changes
Okay, this looks great! Just a few tiny nits, but as soon as these are resolved, I'll approve it 🙂

2023-10-19 04:32 UTC, joshlf commented on src/lib.rs
> +    /// TODO(#429): Add references to docs and quotes.
```suggestion
    ///
    /// TODO(#429): Add references to docs and quotes.
```

2023-10-19 04:32 UTC, joshlf commented on src/lib.rs
> +        // TODO(#429): Add references to docs and quotes.
```suggestion
        //
        // TODO(#429): Add references to docs and quotes.
```

2023-10-19 04:32 UTC, joshlf commented on src/lib.rs
> +        // TODO(#429): Add references to docs and quotes.
```suggestion
        //
        // TODO(#429): Add references to docs and quotes.
```

2023-10-19 04:32 UTC, joshlf commented on src/lib.rs
> +        // TODO(#429): Add references to docs and quotes.
```suggestion
        //
        // TODO(#429): Add references to docs and quotes.
```

2023-10-19 04:32 UTC, joshlf commented on src/lib.rs
> +    /// - `FromZeroes`: Valid since "The value false has the bit pattern
```suggestion
    /// - `FromZeroes`: Valid since "[t]he value false has the bit pattern
```

2023-10-19 04:32 UTC, joshlf commented on src/lib.rs
> +    ///   and "The value false has the bit pattern 0x00 and the value true has
```suggestion
    ///   and "[t]he value false has the bit pattern 0x00 and the value true has
```

2023-10-19 04:32 UTC, joshlf commented on src/lib.rs
> +    /// - `FromZeroes`: Per reference [1], "A value of type char is a Unicode
```suggestion
    /// - `FromZeroes`: Per reference [1], "[a] value of type char is a Unicode
```

2023-10-19 04:32 UTC, joshlf commented on src/lib.rs
> +    /// TODO(#429): Add references to docs and quotes.
```suggestion
    ///
    /// TODO(#429): Add references to docs and quotes.
```

2023-10-21 17:18 UTC, samuelselleck reviewed
Added your changes! I'll make sure to keep spacing and use [] when quoting in the middle of a sentence. merged all commits into one now as well.

2023-10-22 16:44 UTC, joshlf requested changes

2023-10-22 16:44 UTC, joshlf commented on src/lib.rs
> +    /// [1] Per https://doc.rust-lang.org/nightly/core/mem/struct.ManuallyDrop.html:
Looks like these got swapped by accident?

2023-11-04 11:57 UTC, joshlf approved these changes
Thanks again for all your work on this! I cleaned a few things up (deleting spurious extra newlines and such) and it's ready to merge.

2023-11-04 12:13 UTC, merged

2023-11-04 15:29 UTC, samuelselleck commented
Apologies for not getting back to you sooner, thanks for taking the time!

2023-11-04 15:31 UTC, joshlf commented
> Apologies for not getting back to you sooner, thanks for taking the time!

No worries at all! I was just going back and cleaning up old PRs and I figured it was silly to ask you to do a few obvious edits when I was doing it already 🙂