feat : Add positive and negative trait impl tests for SIMD types #130
google/zerocopy pull request #487
Opened 2023-10-11 05:26 UTC by Sh0g0-1758

Hey, this is my first open-source contribution. I have added the tests as instructed to the best of my knowledge. Please do suggest changes to it if you find something wrong.

2023-10-11 13:45 UTC, jswrenn requested changes
Thank you! This looks good. A few minor changes are required to get this passing CI, and you'll also need to sign the Google CLA.

2023-10-11 13:45 UTC, jswrenn commented on src/lib.rs
> +                        $( assert_impls!($ty: KnownLayout, FromZeroes, FromBytes, AsBytes, !Unaligned); )*
```suggestion
                        $( assert_impls!($typ: KnownLayout, FromZeroes, FromBytes, AsBytes, !Unaligned); )*
```

2023-10-11 13:45 UTC, jswrenn commented on src/lib.rs
Can you run `cargo fmt`? This PR is currently failing the CI formatting check: https://github.com/google/zerocopy/actions/runs/6478364799/job/17590006383?pr=487

2023-10-12 04:15 UTC, Sh0g0-1758 commented on src/lib.rs
> +                        $( assert_impls!($ty: KnownLayout, FromZeroes, FromBytes, AsBytes, !Unaligned); )*
Fixed this issue.

2023-10-12 04:15 UTC, Sh0g0-1758 commented on src/lib.rs
ran the command and pushed the formatted code.

2023-10-12 04:38 UTC, Sh0g0-1758 commented
@jswrenn , I have made the changes and all the CLI checks are passing. Can you please review it once.

2023-10-17 11:32 UTC, joshlf approved these changes

2023-10-17 14:35 UTC, Sh0g0-1758 commented
@joshlf, it seems that the merge did not happen.

2023-10-17 16:43 UTC, joshlf commented
> @joshlf, it seems that the merge did not happen.

This is failing due to an unrelated error: https://github.com/rust-lang/miri/issues/3125. I'll merge manually.

2023-10-17 16:44 UTC, merged