Fix Ref::new_slice_from_suffix()
google/zerocopy pull request #506
Opened 2023-10-13 20:21 UTC by dmitryash

`new_slice_from_suffix()` has a bug and implemented exactly as `new_slice_from_prefix()`. Now part of buffer is chosen right.

Tests couldn't have caught because buffer was just zeros. Now buffer is not just zeros so that tests can prove correctness of `new_slice_from_suffix()`.

2023-10-15 18:07 UTC, joshlf requested changes
Awesome, thanks so much for catching this! One small change to request. I want to give some more thought to whether we should do more to beef up our tests in this PR to catch bugs like this in the future; I'll have time to do that and give more detailed feedback early this coming week.

2023-10-15 18:07 UTC, joshlf commented on src/lib.rs
> +        let (bytes, suffix) = bytes.split_at(position);
To be consistent with the implementation of `new_from_suffix`:

```suggestion
        let split_at = bytes.len().checked_sub(expected_len)?;
        let (bytes, suffix) = bytes.split_at(split_at);
```

2023-10-16 14:41 UTC, joshlf commented
Not sure what's up with those failing Miri test cases. Maybe try rebasing on `main`? If that doesn't work, we can investigate in more depth.

2023-10-16 15:11 UTC, joshlf commented
I've uploaded #511, which follows on this to beef up `test_new_aligned_sized` a bit. Once CI passes for this, I'll approve and merge and then rebase #511 on top of this.

2023-10-16 15:19 UTC, joshlf commented
Note that we plan to follow up on this consistent with #512.

2023-10-16 18:50 UTC, joshlf approved these changes

2023-10-16 19:02 UTC, joshlf commented
It appears that Miri is failing nondeterministically. I've reported the issue here: https://github.com/rust-lang/miri/issues/3125. This appears to be an issue with Miri rather than with our code, so I'll try a few more times and maybe we'll get lucky with this making it through the merge queue. Obviously we'll need to fix this issue fairly soon, but there's no reason for resolving that issue to block this PR.

2023-10-16 19:20 UTC, merged

2023-10-16 19:21 UTC, joshlf commented
@dmitryash Out of curiosity, how did you stumble upon this issue? We're always curious to hear how zerocopy is getting used in the wild!

2023-10-22 19:19 UTC, dmitryash commented
@joshlf I needed to decode some data that has "footer" and I tried from_suffix variant but found that it did not work correctly.

2023-10-22 19:31 UTC, joshlf commented
> @joshlf I needed to decode some data that had "footer" and I tried from_suffix variant but found that it did not work correctly.

Interesting, can you say more about why it didn't work? I'd like to be able to support your use case if possible.