[macro_util] Simplify core_reexport
google/zerocopy pull request #562
Opened 2023-10-27 22:21 UTC by joshlf

2023-10-27 22:23 UTC, jswrenn requested changes

2023-10-27 22:23 UTC, jswrenn commented on src/macro_util.rs
>  }
Instead of all this, why not:
```
pub use ::core as core_reexport;
```

2023-10-27 22:24 UTC, joshlf commented on src/macro_util.rs
>  }
Good call, done.

2023-10-27 22:26 UTC, jswrenn approved these changes

2023-10-30 15:18 UTC, jswrenn commented
I believe the semver-checks failure is a false-positive, and I've filed a bug report: https://github.com/obi1kenobi/cargo-semver-checks/issues/573

2023-11-02 13:04 UTC, closed without merging

2023-11-02 13:06 UTC, joshlf commented
Closed in favor of https://github.com/google/zerocopy/pull/586.