Initial commit of NoCell
google/zerocopy pull request #656
Opened 2023-11-28 22:46 UTC by joshlf

Makes progress on #251

2023-12-04 15:47 UTC, jswrenn commented on src/lib.rs
> +    /// `Option<T>` where `T: NoCell`).
Don't you already do this on line 3623?

2023-12-04 18:34 UTC, joshlf commented on src/lib.rs
> +    /// `Option<T>` where `T: NoCell`).
Oops, stale comment. Removed.

2023-12-04 19:00 UTC, jswrenn requested changes

2023-12-06 20:32 UTC, jswrenn submitted a review, later dismissed

2023-12-06 20:32 UTC, joshlf commented on src/lib.rs
> +/// (e.g., `UnsafeCell<()>`). If a type implements `NoCell` which violates this
Good point, updated.

2023-12-06 20:44 UTC, merged