Traits other than `NoCell` permit `UnsafeCell`s
google/zerocopy pull request #682
Opened 2023-12-06 23:32 UTC by joshlf

Previously, `FromZeros`, `FromBytes`, and `AsBytes` could not be
implemented for types containing `UnsafeCell`s. This is a soundness
precondition for some types of reference transmutations (notably
transmuting either direction between `&[u8]` and `&T`). However, some of
our machinery operates only on values (e.g. `transmute!`), and that
machinery should in principle be able to support types which contain
`UnsafeCell`s.

In this commit, we remove the "no `UnsafeCell`" restriction from
`FromZeros`, `FromBytes`, and `AsBytes`. We use the recently-added
`NoCell` trait as a bound on individual functions and methods where
`UnsafeCell`s would be unsound. This permits some APIs to support
`UnsafeCell`s which could not previously support them.

Closes https://github.com/google/zerocopy/issues/251

2023-12-07 00:12 UTC, joshlf commented on src/lib.rs
> +        Self: NoCell,
Ideally we wouldn't need this bound, but I'm not sure how to implement this method soundly without it. Thankfully this isn't a regression (in 0.7.X, `AsBytes` forbids `UnsafeCell`s full stop). However, at a minimum, we may want to file an issue to track eventually relaxing this bound (and the `NoCell` bound on other `write_to_xxx` methods).

2023-12-07 22:58 UTC, joshlf commented on src/lib.rs
> +        Self: NoCell,
Filed https://github.com/google/zerocopy/issues/688 to track.

2023-12-08 16:30 UTC, jswrenn requested changes

2023-12-08 16:52 UTC, joshlf commented on src/lib.rs
> +    /// representations as `[u8]`, `T`, and `T` repsectively. `str` has
Done.

2023-12-08 17:35 UTC, jswrenn approved these changes

2023-12-08 17:43 UTC, merged