Add check_msrv job to ci workflow
google/zerocopy pull request #70
Opened 2022-10-16 21:39 UTC by memark

Add check_msrv job to ci workflow. Checking the MSRV specified in all the places mentioned in #39:

- Doc comment in src/lib.rs
- .github/workflows/ci.yml
- tests/trybuild.rs (added in https://github.com/google/zerocopy/pull/60, which hasn't merged as of this writing)
- zerocopy-derive/tests/trybuild.rs

I have run this logic locally against #60 as well and it works.

Resolves #39.

2022-10-16 22:09 UTC, joshlf commented
Thanks, @memark! I'll give this a review once the CI tests are passing.

2022-10-17 15:51 UTC, AntoniosBarotsis commented
Hello!

I tried messing around with this for a bit cause I saw you were getting an error with no error message.

I see you used `'.jobs.build_test.strategy.matrix.channel[0]'` somewhere, I couldn't figure out how to get matrix variables from a different job but one (albeit slightly messy) workaround would be to define a top-level env variable with the first channel and then use that in both the matrix and in the MSRV step.

I tried doing that [here](https://github.com/AntoniosBarotsis/zerocopy/blob/check_msrv_testing/.github/workflows/ci.yml) but I am still getting some errors (this time with error messages!) and here are the [logs](https://github.com/AntoniosBarotsis/zerocopy/actions/runs/3266572209/jobs/5370496402). Not sure if this is of any help but I hope so :)

2022-10-17 18:27 UTC, memark commented
Thanks, that's an interesting approach! @AntoniosBarotsis 

Something I struggled/hesitated a bit about is where the "true" MSRV really lives? If there is one? Right now I'm pretty much only comparing all versions I can extract.

I did find out why there where no error messages btw, it was that pesky "set -e" that I blindly copied from the other jobs... After one afternoon of trials in my own repo I finally figured that one out.

2022-10-17 18:45 UTC, joshlf commented
> Something I struggled/hesitated a bit about is where the "true" MSRV really lives? (If there is one?)
> Right now I'm pretty much only comparing all versions I can extract. Could this variable be it? (Is the workflow the place where we'd want to store it?)

I originally tried to have a source of truth in an `MSRV.txt` file (see https://github.com/google/zerocopy/issues/39#issue-1402438366). I even tried to have a source of truth just in the scope of the `ci.yml` file, and [discovered that that would also be really difficult to do ergonomically](https://stackoverflow.com/questions/74072206/github-actions-use-variables-in-matrix-definition/74073435#74073435). That's why I figured that "the same MSRV in all of the files" might be the best we could do without a lot of over-engineering.

2022-10-18 06:16 UTC, memark commented
> That's why I figured that "the same MSRV in all of the files" might be the best we could do without a lot of over-engineering.

Understood. I've gone with this approach as well now. I think the workflow should pass now, please allow it to run.

2022-10-18 17:58 UTC, joshlf requested changes
Hey, sorry about the churn on this one, but I just had a realization:
- Looking for all MSRVs is pretty brittle because it relies on the exact format of a number of different files; e.g., I could use a different expression in the `trybuild.rs` files, and all of a sudden the `grep`s we're running on those files would just output nothing, which would cause this script to continue to succeed
- It would probably be fine to not look at the `trybuild.rs` files - if we get the MSRV there wrong, all that will happen is that at worst the tests will fail, which we'll notice and fix
- We'd like to do `set -e` to catch any errors in the script, but we can't so long as `tests/trybuild.rs` doesn't exist yet
- The thing we really need to check for - the thing that would be bad if we missed - is if we're testing for a different MSRV in `ci.yml` than the one we have advertised in the doc comment in `src/lib.rs`

With all that in mind, how would you feel about making the following changes?
- Doing `set -e` at the top
- Only checking that the MSRV in `src/lib.rs` matches the one in `ci.yml`

2022-10-18 18:20 UTC, joshlf commented
> Sure, I'll make those changes.

Thanks!

> I will add though that it would have saved me a lot of time and energy if I knew that all that was required was comparing _two_ version numbers (out of the _six_ present in the locations listed in the issue).

Yeah, sorry about that 🙁  Didn't realize that this was the right approach until you'd already put up the code.

> As for `set -e` I think it makes more sense in a script that does side-effectful actions, and less in a query-based script like this. It also has the effect that if something fails (e.g. `grep`) all you get is "-1" without much explanation.

In this particular case, we expect `grep` to never return a non-zero code, right? It should always find at least one matching line, so if it doesn't, we should see that error and the test should fail.

> Since the `src/lib.rs` comment is not yet available in `main`, and we want `set -e`, should I then write a version of the script that doesn't work until #60 is merged? Or just wait?

It's up to you. I think you could also just include an MSRV section in `src/lib.rs` in this PR - if it merges before #60, then cool. If it doesn't, then we can rebase. But you could also just wait until #60 merges. Up to you!

2022-10-19 06:27 UTC, memark commented
Just pushed a simplified version of the msrv check. Ready for review.

2022-10-19 17:26 UTC, joshlf requested changes
Awesome, thanks for this, @memark! Just a few nit-pick comments, but this looks great!

2022-10-19 19:31 UTC, memark commented on .github/workflows/ci.yml
> +          ver_ci=$(<.github/workflows/ci.yml yq '.jobs.build_test.strategy.matrix.channel[0] // ""' | grep .)
No, it's not for symmetry. `yq` by default returns `null` when nothing is found. This is then coalesced into empty string (`// ""`). Finally `| grep .` only allows actual values to pass through. (In short, I find it easier to work with an empty variable than with one saying "null".)

2022-10-19 19:32 UTC, memark commented on .github/workflows/ci.yml
> +            echo "Different MSRVs found in checked places." | tee -a $GITHUB_STEP_SUMMARY
Sure.

2022-10-19 19:32 UTC, memark commented on .github/workflows/ci.yml
> +  check_msrv:
Sure.

2022-10-19 19:37 UTC, memark commented on .github/workflows/ci.yml
> +            echo "Same MSRV found in both places." | tee -a $GITHUB_STEP_SUMMARY
Sure.

2022-10-19 20:42 UTC, joshlf commented on .github/workflows/ci.yml
> +          ver_ci=$(<.github/workflows/ci.yml yq '.jobs.build_test.strategy.matrix.channel[0] // ""' | grep .)
Oh gotcha that makes sense.

2022-10-19 21:01 UTC, joshlf approved these changes
Confirmed in #79 that this test catches an MSRV mismatch:

![Screen Shot 2022-10-19 at 1 59 54 PM](https://user-images.githubusercontent.com/1046063/196803188-dcf0de00-b65c-42eb-a1c3-7da6338a0ce2.png)

Thanks again for all your work on this, @memark!

2022-10-19 21:02 UTC, merged

2022-10-19 21:48 UTC, memark commented
Happy to help out!