Add caching dupe change
google/zerocopy pull request #835
Opened 2024-02-03 08:57 UTC by dorryspears

This closes #340.  I tried putting the yaml in the workflow folder for the new cache job but it wasn't able to find it, so I made it an action.

2024-02-11 05:22 UTC, joshlf commented
Thanks for this, @dorryspears !

I'm not a GitHub Actions expert, so I may be off the mark here, but will making this a "step" rather than a `needs` dependency mean that this action is executed multiple times? Currently (on `main`), it executes once at the beginning of the job run and then the results are re-used by all steps, which helps things run faster.

2024-02-12 21:45 UTC, dorryspears commented
@joshlf You are right.  I now understand what the CI was doing.  I rearranged my code and added back the generate cache step.  That action just replaces the 

```yaml
- uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      with:
        path: |
          ~/.cargo/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
``` 
step in the existing jobs.

2024-02-13 00:17 UTC, joshlf requested changes
Okay awesome, thanks! A few nits regarding stray whitespace, but this looks good!

2024-02-13 00:17 UTC, joshlf commented on .github/workflows/ci.yml
> +
```suggestion

```

2024-02-13 00:17 UTC, joshlf commented on .github/workflows/ci.yml
> +
```suggestion

```

2024-02-13 00:17 UTC, joshlf commented on .github/workflows/ci.yml
> +
```suggestion

```

2024-02-13 00:26 UTC, joshlf approved these changes

2024-02-13 19:06 UTC, merged