Lower MSRV to 1.56
google/zerocopy pull request #855
Opened 2024-02-08 21:38 UTC by joshlf

Makes progress on #554

2024-02-08 22:01 UTC, jswrenn requested changes

2024-02-08 22:11 UTC, joshlf commented on src/lib.rs
> +            None => loop {},
Done.

2024-02-10 03:05 UTC, jswrenn approved these changes

2024-02-10 03:33 UTC, jswrenn approved these changes

2024-02-10 03:58 UTC, jswrenn approved these changes

2024-02-10 04:05 UTC, merged