Relax safety precondition of `Ptr::cast_unsized`
google/zerocopy pull request #999
Opened 2024-03-02 03:53 UTC by jswrenn

We relax the `UnsafeCell` safety conditions on `cast_unsized` for exclusively-aliased pointers. This paves the way for removing the `NoCell` bound from `try_cast_into`, `try_cast_into_no_leftover`, and finally from `TryFromBytes::try_from_mut`.

I *think* this is sound; putting this PR up so we can discuss @joshlf.

2024-03-05 20:42 UTC, joshlf requested changes

2024-03-05 20:42 UTC, joshlf commented on src/pointer/ptr.rs
> +        /// - If the aliasing of `self` is Shared, projected pointer must
```suggestion
        /// - If the aliasing of `self` is not `Exclusive`, projected pointer must
```

2024-03-05 20:42 UTC, joshlf commented on src/pointer/ptr.rs
> +        /// - if the aliasing of `self` is Shared, that `UnsafeCell`s in `U`
```suggestion
        /// - if the aliasing of `self` is not `Exclusive`, that `UnsafeCell`s in `U`
```

2024-03-05 20:42 UTC, joshlf commented on src/pointer/ptr.rs
> +            //     - If `ptr` is exclusively aliased, no other references exist.
```suggestion
            //     - If `ptr` is exclusively aliased, no other live references exist.
```

2024-03-05 20:42 UTC, joshlf commented on src/pointer/ptr.rs
> +        /// 11. During the lifetime 'a, no live reference will exist to this
```suggestion
        /// 11. During the lifetime 'a, no live reference and no live `Ptr` will exist to this
```

2024-03-05 20:46 UTC, jswrenn commented on src/pointer/ptr.rs
> +        /// - If the aliasing of `self` is Shared, projected pointer must
Done

2024-03-05 20:46 UTC, jswrenn commented on src/pointer/ptr.rs
> +            //     - If `ptr` is exclusively aliased, no other references exist.
Done

2024-03-05 20:46 UTC, jswrenn commented on src/pointer/ptr.rs
> +        /// - if the aliasing of `self` is Shared, that `UnsafeCell`s in `U`
Done

2024-03-05 20:46 UTC, jswrenn commented on src/pointer/ptr.rs
> +        /// 11. During the lifetime 'a, no live reference will exist to this
Done

2024-03-05 20:50 UTC, joshlf requested changes
Anywhere that we reason about `UnsafeCell` non-overlap being okay in virtue of exclusive aliasing, we should add:

```rust
// TODO(#896), TODO(https://github.com/rust-lang/unsafe-code-guidelines/issues/495): Blah
// blah blah before the next stable release.
```

2024-05-09 19:17 UTC, jswrenn commented
Superseded by #1211.

2024-05-09 19:17 UTC, closed without merging